/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package echipamentbucatarie;

import java.util.ArrayList;
import javax.swing.JFrame;


/**
 *
 * @author Mazilu Alex
 */
public class Proiect extends javax.swing.JFrame {

    /**
     * Creates new form Proiect
     */
    public Proiect() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
                       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMinim = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(38, 166, 91));

        jLabelClose.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabelMinim.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelMinim.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMinim.setText("_");
        jLabelMinim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Magazin Electrocasnice");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 458, Short.MAX_VALUE)
                .addComponent(jLabelMinim, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelClose, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClose)
                    .addComponent(jLabelMinim)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 398, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMinimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimMouseClicked

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        ArrayList<Frigider> frigidere = new ArrayList<Frigider>();
                frigidere.add(new Frigider("Whirlpool","Gri",800,25,false,1,4,"A+",false,false));
                frigidere.add(new Frigider("Arctic","Negru",1600,30,true,2,3,"A++",true,false));
                frigidere.add(new Frigider("Albatros","Alb",799,40,false,2,6,"B",false,true));
                frigidere.add(new Frigider("Beko","Negru",980,90,true,3,6,"A++",true,true));
                frigidere.add(new Frigider("Whirpool","Alb",890,37,false,2,1,"A++",true,false));
                frigidere.add(new Frigider("Samsung","Alb",2000,30,true,2,3,"A+++",true,true));
                frigidere.add(new Frigider("Whirpool","Negru",400,50,true,2,5,"A+",true,true));
                frigidere.add(new Frigider("Indesit","Alb",660,40,true,2,3,"A++",true,false));
                frigidere.add(new Frigider("Arctic","Gri",500,50,false,1,5,"B+",false,true));
                frigidere.add(new Frigider("Beko","Alb",890,40,false,3,4,"A+",true,false));
                frigidere.add(new Frigider("Samsung","Gri",700,40,false,1,3,"B++",true,false));
                frigidere.add(new Frigider("Albatros","Gri",599,40,true,2,2,"A+",false,true));
                frigidere.add(new Frigider("Whirpool","Alb",489,35,false,2,3,"C++",false,false));
                frigidere.add(new Frigider("Indesit","Negru",1899,55,true,3,4,"A+++",true,true));
                frigidere.add(new Frigider("Hansa","Gri",650,40,false,2,3,"A",true,false));
                frigidere.add(new Frigider("Arctic","Alb",869,45,false,1,5,"B++",true,true));
                frigidere.add(new Frigider("Whirpool","Gri",669,45,true,2,4,"A+",false,true));
                frigidere.add(new Frigider("Hansa","Negru",959,60,true,3,4,"A++",true,true));
                frigidere.add(new Frigider("Hansa","Alb",750,45,false,2,3,"A",true,false));
                frigidere.add(new Frigider("Beko","Gri",850,50,true,1,5,"A",false,true));
            
            
            
                ArrayList<CombinaFrigorifica> combine=new ArrayList<CombinaFrigorifica>();
                combine.add(new CombinaFrigorifica("LG","Alb",10,12,false,"No Frost","Automat","Emag",35,true));
                combine.add(new CombinaFrigorifica("Beko","Gri",10,12,true,"Neo Frost","Manual","Demax",34,true));
                combine.add(new CombinaFrigorifica("Whirpool","Negru",10,12,false,"FrostLess","Semi-Automat","Flanco",30,false));
                combine.add(new CombinaFrigorifica("Albatros","Alb",10,12,true,"Dinamic","Automat","Emag",41,true));
                combine.add(new CombinaFrigorifica("Indesit","Negru",10,12,false,"SmartFrost","Manual","Flanco",45,false));
                combine.add(new CombinaFrigorifica("Hansa","Gri",10,12,false,"Full No Fross","Automat","Demax",36,true));
                combine.add(new CombinaFrigorifica("Samsung","Alb",10,12,true,"Fross","Semi-Automat","Emag",33,false));
                combine.add(new CombinaFrigorifica("Whirpool","Negru",10,12,true,"Neo Frost","Manual","Flanco",32,true));
                combine.add(new CombinaFrigorifica("Indesit","Gri",10,12,false,"FrostLess","Automat","Emag",35,true));
                combine.add(new CombinaFrigorifica("Beko","Gri",10,12,true,"SmartFrost","Semi-Automat","Emag",30,false));
                combine.add(new CombinaFrigorifica("LG","Alb",10,12,true,"Dinamic","Manual","Emag",38,true));
                combine.add(new CombinaFrigorifica("Samsung","Negru",10,12,true,"Full No Fross","Automat","Flanco",39,false));
                combine.add(new CombinaFrigorifica("Albatros","Gri",10,12,false,"SmartFrost","Automat","Demax",36,true));
                combine.add(new CombinaFrigorifica("LG","Negru",10,12,false,"Neo Frost","Semi-Automat","Emag",32,true));
                combine.add(new CombinaFrigorifica("Beko","Alb",10,12,true,"Full No Fross","Automat","Flanco",44,false));
                combine.add(new CombinaFrigorifica("Hansa","Gri",10,12,false,"SmartFrost","Semi-Automat","Demax",43,true));
                combine.add(new CombinaFrigorifica("LG","Alb",10,12,true,"Dinamic","Manual","Emag",41,true));
                combine.add(new CombinaFrigorifica("Whirpool","Gri",10,12,false,"FrostLess","Manual","Emag",47,false));
                combine.add(new CombinaFrigorifica("Indesit","Negru",10,12,true,"Full No Fross","Automat","Flanco",41,true));
                combine.add(new CombinaFrigorifica("Beko","Alb",10,12,false,"SmartFrost","Manual","Emag",36,true));
                
                
                
                ArrayList<CuptorMicrounde> microunde = new ArrayList<CuptorMicrounde>();
                microunde.add(new CuptorMicrounde("ADLER","Gri",360,23,false,"Microunde","800W","Inox",9.7f,4)); 
                microunde.add(new CuptorMicrounde("Samsung","Gri",380,23,false,"Microunde","1000W","Ceramica",10.2f,5)); 
                microunde.add(new CuptorMicrounde("Whirlpool","Gri",600,20,true,"Cu abur","900W","Ceramica",10.7f,6)); 
                microunde.add(new CuptorMicrounde("Daewoo","Gri",270,20,false,"Microunde","800W","Inox",9.1f,4)); 
                microunde.add(new CuptorMicrounde("BOSCH","Gri",380,20,false,"Grill","700W","Inox",10,4)); 
                microunde.add(new CuptorMicrounde("BEKO","Gri",450,25,false,"Convectie","800W","Ceramica",10,6)); 
                microunde.add(new CuptorMicrounde("ADLER","Negru",500,20,false,"Microunde","900W","Ceramica",11.3f,6)); 
                microunde.add(new CuptorMicrounde("Samsung","Negru",440,23,true,"Microunde","770W","Ceramica",10,4)); 
                microunde.add(new CuptorMicrounde("Whirlpool","Negru",550,23,false,"Grill","800W","Ceramica",10.3f,5)); 
                microunde.add(new CuptorMicrounde("Daewoo","Negru",360,23,false,"Grill","1000W","Inox",10,4));
                microunde.add(new CuptorMicrounde("BOSCH","Negru",380,20,true,"Cu abur","900W","Inox",9.7f,4)); 
                microunde.add(new CuptorMicrounde("BEKO","Negru",500,20,false,"Microunde","100W","Ceramica",11.2f,6)); 
                microunde.add(new CuptorMicrounde("ADLER","Argintiu",360,20,false,"Convectie","770W","Inox",10,5)); 
                microunde.add(new CuptorMicrounde("Samsung","Argintiu",490,23,true,"Microunde","800","Ceramica",10,6)); 
                microunde.add(new CuptorMicrounde("Whirlpool","Argintiu",700,25,true,"Cu abur","970W","Ceramica",12.1f,6)); 
                microunde.add(new CuptorMicrounde("Daewoo","Argintiu",380,25,true,"Grill","800W","Inox",10,5)); 
                microunde.add(new CuptorMicrounde("BOSCH","Argintiu",500,23,false,"Microunde","1080W","Ceramica",10,6)); 
                microunde.add(new CuptorMicrounde("BEKO","Argintiu",360,23,false,"Microunde","1080W","Inox",10,5)); 
                microunde.add(new CuptorMicrounde("ADLER","Alb",360,25,true,"Convectie","700W","Inox",10,5)); 
                microunde.add(new CuptorMicrounde("Samsung","Alb",500,23,true,"Cu abur","900","Ceramica",11.6f,6)); 
                microunde.add(new CuptorMicrounde("Whirlpool","Alb",650,23,false,"Microunde","1080W","Ceramica",10,6)); 
                microunde.add(new CuptorMicrounde("Daewoo","Alb",360,25,true,"Microunde","770W","Inox",10,4)); 
                microunde.add(new CuptorMicrounde("BOSCH","Alb",500,23,true,"Microunde","800W","Ceramica",12,6)); 
                microunde.add(new CuptorMicrounde("BEKO","Alb",270,16,false,"Grill","700W","Inox",8.7f,4)); 
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proiect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proiect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proiect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proiect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proiect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMinim;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
